@echo off
echo Running data curation...
python scripts/clean_curate.py
echo Running validation...
python scripts/validate_curated.py
echo Generating visualizations...
python scripts/visualize_data.py
echo Creating project logo...
python scripts/create_logo.py
echo Generating PDF article...
python scripts/markdown_to_pdf.py
echo Running tests...
python -m pytest tests/ -v
echo All tasks completed!